### ISSUE TITLE
Support for psycopg3

### ISSUE THREAD

**Issue by ckcollab** [Opus10/django-pgbulk#18]
Hey there, thanks so much for this library! Do you plan to add support for psycopg==3.1.8? I gave it a shot myself in a fork, but I'm not sure where or what "AsIs" is inside the new version of psycopg. I'm wondering if I can install psycopg2-binary alongside the new version, and things may "just work?"

**Comment by wesleykendall** [comment]
Fixed in v1.4.0!

**Comment by ckcollab** [comment]
thank you so much!
